name: setup-node

on:
  workflow_call:

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
        key: node_modules_${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }} # Use hash of package-lock.json for the key
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      if: ${{ steps.cache_dependencies.outputs.cache-hit != 'true' }}
      shell: bash
      run: npm ci
